version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  default: standard
  enable:
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - errorlint
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - prealloc
    - unconvert
    - unparam
    - whitespace

  settings:
    gocyclo:
      min-complexity: 15
    gocognit:
      min-complexity: 20
    dupl:
      threshold: 100
    goconst:
      min-len: 3
      min-occurrences: 3
    misspell:
      locale: US
    gocritic:
      enabled-tags:
        - diagnostic
        - performance
        - style

  exclusions:
    rules:
      # Exclude some linters from running on test files
      - path: _test\.go$
        linters:
          - dupl
          - gosec
          - gocyclo
          - gocognit

formatters:
  enable:
    - gofmt
    - goimports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
